# Generated by Django 4.0 on 2022-01-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ded_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('img', models.ImageField(upload_to='image/media/')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
            },
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='jear',
            options={'verbose_name': 'Год', 'verbose_name_plural': 'Года'},
        ),
        migrations.AlterField(
            model_name='foto',
            name='img',
            field=models.ImageField(upload_to='image/media/'),
        ),
    ]
